# .yml & .yaml 真的腊(垃)鸡(圾)，怎么会有这么多人喜欢用......
# 不能用 Tab 制表符，只能打两个空格
# 官方文档就像20世纪上半叶用大屁股写的CSS

version: "3.7"

services:
  db:
    container_name: mysql
    image: mysql:8.0.18
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./deploy.sql:/docker-entrypoint-initdb.d/deploy.sql

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tomcat
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test?serverTimezone=UTC
    links:
      - db
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "python", "app.py"]
